name: main_workflow.yml

on: [push]
jobs:
  prueba:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Super-linter
          uses: github/super-linter@latest
          env:
            LINTER_RULES_PATH: /
            VALIDATE_ALL_CODEBASE: true
            DEFAULT_BRANCH: main
            JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
            VALIDATE_JAVASCRIPT_ES: true
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
