name: Modify Readme Workflow
on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          npm install
          npm test

  modify_readme:
    needs: run_tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Modify Readme
        uses: ./
        with:
          positive_phrase: 'Los tests han funcionado y lo sabes'
          negative_phrase: 'Los tests no han funcionado y lo sabes'
          result_tests: ${{ needs.run_tests.outputs.result }}
      - name: Commit and push
        run: |
          git config --local user.email "soro_24@hotmail.com"
          git config --local user.name "Lordsoro"
          git add README.md
          git commit -m "Add meme to README"
          git push
 
